steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/linkslogic-backend', 
      '.'
    ]
  
  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'gcr.io/$PROJECT_ID/linkslogic-backend'
    ]
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'linkslogic-backend',
      '--image', 'gcr.io/$PROJECT_ID/linkslogic-backend',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '5001'
    ]

# This fixes your service account + logging error
options:
  logging: CLOUD_LOGGING_ONLY
